[[TOP]]
= Hiking Routes Database =
:author: Mats Landgren
'''

[[L1]]
== Background
I do a lot of hiking, especially in weird places where there are no infrastructure for walkers (marked trails, signboards, tourist maps, etc). This requires a lot of planning. For this purpose I have created a link:http://www.karpaterna.se/trailexplorer[map tool] where I can draw paths on top of various maps and GPS tracks. The tool will then calculate the distance along these paths, the elvetation gain/loss and an approximate hiking time. (I use a formula known as link:https://en.wikipedia.org/wiki/Tobler%27s_hiking_function[Tobler's hiking function] to calculate the hiking time.)

I would like to set up a database full of waypoints that are connected by a network of trails. When I want to go hiking somewhere, I can ask the database what route I should choose if I want to find the fastest way between two waypoints. If I have bad knees, I can ask for the route with the minimum amount of downhill walking. The more properties I can add to the wapoints and trails, the more possibilities I would have for finding routes based on diffetent criteria.

[[L2]]
=== Graph Population 
Click the + to see the full set-up Cypher script.
//setup
//hide
[source,cypher]
----
CREATE 
//define waypoints
(wp1:Waypoint{name:'Billinge',elevation:'300m',type:'bus stop'}),
(wp2:Waypoint{name:'Odensjön',elevation:'500m',type:'lake'}),
(wp3:Waypoint{name:'Dahlbergs stuga',elevation:'430m',type:'hut'}),
(wp4:Waypoint{name:'Hjortsprånget',elevation:'120m',type:'view point'}),
(wp5:Waypoint{name:'Naturrum',elevation:'810m',type:'café'}),
(wp6:Waypoint{name:'Kopparhatten',elevation:'710m',type:'viewpoint'}),
(wp7:Waypoint{name:'Klippan',elevation:'210m',type:'bus stop'}),

// define trail sections
(wp1)-[:TRAIL{km:4,minutes:65, elevationgain:120, elevationloss:78}]->(wp2),
(wp2)-[:TRAIL{km:3.5,minutes:52, elevationgain:33, elevationloss:34}]->(wp3),
(wp2)-[:TRAIL{km:0.1,minutes:5, elevationgain:23, elevationloss:194}]->(wp4),
(wp3)-[:TRAIL{km:0.5,minutes:17, elevationgain:54, elevationloss:56}]->(wp4),
(wp4)-[:TRAIL{km:3.1,minutes:54, elevationgain:183, elevationloss:11}]->(wp5),
(wp4)-[:TRAIL{km:1.8,minutes:23, elevationgain:712, elevationloss:72}]->(wp6),
(wp5)-[:TRAIL{km:7.2,minutes:112, elevationgain:12, elevationloss:109}]->(wp7),
(wp6)-[:TRAIL{km:2.7,minutes:32, elevationgain:69, elevationloss:8}]->(wp7)

----

[[L3-2]]
=== Graph Visualisation
This shows the results of the above set-up script.
//graph

[[L4-2-x]]
==== What is the shortest route from Billinge to Klippan <<TOP, ^Top^>>
This query calculates the shortest route between the two specified nodes. This is the shortest route based upon the number of traversals in the graph, and not upon the distance property on the relationships being traversed. This is the shortest route in the graph, not in reality. The next question deals with actual distance.

Because there is more than one possible start and end node I have used LENGTH(), ORDER BY and LIMIT to return just the shortest route (calculated by the number of traversals). I did this before the RETURN statement, so that I did not have to return the count, which I would have to have done if ordering by count after the RETURN statement.
[source,cypher]
----
MATCH p=shortestPath((a:Location)-[trail.km*]->(b:Location))
WHERE a.name = 'Billinge'
AND b.name = 'Klippan'
RETURN p AS route
----
//table

[[L4]]
== The Next Step <<TOP, ^Top^>>
In order to calculate a route between two waypoints, I would need some formulas and express them in the Cypher language. I did find link:http://gist.neo4j.org/?8635758[this example] on your website which performs similar actions.

<<TOP, Back to top>>
